version: "3.3"

services:
  myapp:
    image: openjdk:20-jdk-bullseye
    container_name: "whey-scraper"
    restart: always
    ports:
      - 8091:8091
    volumes:
      - "./:/app"
    command: ["java", "-jar", "/app/wheybot.jar"]