version: "3.3"

services:
  myapp:
    image: openjdk:8-jdk-alpine
    container_name: "whey-scraper"
    restart: always
    ports:
      - 8091:8091
    volumes:
      - "./bin/com/davidpoza/wheybot.jar:/app.jar"
    command: ['java', '-jar', '/app.jar']